grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2
model_selection:
  module_0:
    class: LinearRegression
    module: sklearn.linear_model
    params:
      fit_intercept: true
    search_param_grid:
      fit_intercept:
      - true
      - false
  module_1:
    class: RandomForestRegressor
    module: sklearn.ensemble
    params:
      criterion : squared_error
      min_samples_split: 2
      min_samples_leaf: 2
      n_jobs: -1
    search_param_grid:
       criterion :
         - absolute_error
         - poisson
       min_samples_split:
         - 3
       min_samples_leaf: 
         - 3 
  module_2:
    class: DecisionTreeRegressor
    module: sklearn.tree
    params:
       criterion : squared_error
       min_samples_split: 2
       min_samples_leaf: 2
       n_jobs: -1
    search_param_grid:
       criterion : 
         - absolute_error
         - poisson
       min_samples_split:
         - 3
       min_samples_leaf:
         - 3 
  module_3:
    class: AdaBoostRegressor
    module: sklearn.ensemble
    params:
       loss : linear
    search_param_grid:
       loss :
         - square
         - exponential   